In [61]:
import pandas as pd

In [62]:
df = pd.read_csv('Education.csv')

In [63]:
df = df[['districtID']]

In [64]:
import re 
state = []
districtNum = []
for idx, row in df.iterrows():
    res = [re.findall(r'(\w+?)(\d+)', row['districtID'])[0]]
    st = res[0][0]
    if '_' in st:
        lst = st.split('_')
        temp = ''
        for i in range(len(lst)):
            temp += lst[i].capitalize()
            if i == 0:
                temp += ' '
        state.append(temp)
    else:
        state.append(st.capitalize())
    districtNum.append(res[0][1])

In [65]:
df['state'] = state
df['congressionalDistrictNum'] = districtNum

In [67]:
df = df.set_index('districtID')

In [68]:
df.to_csv('Districts.csv')

In [69]:
df

                        state congressionalDistrictNum
districtID
alabama1              Alabama                        1
alabama2              Alabama                        2
alabama3              Alabama                        3
alabama4              Alabama                        4
alabama5              Alabama                        5
alabama6              Alabama                        6
alabama7              Alabama                        7
alaska1                Alaska                        1
arizona1              Arizona                        1
arizona2              Arizona                        2
arizona3              Arizona                        3
arizona4              Arizona                        4
arizona5              Arizona                        5
arizona6              Arizona                        6
arizona7              Arizona                        7
arizona8              Arizona                        8
arizona9              Arizona                        9
arkansas1            Arkansas                        1
arkansas2            Arkansas                        2
arkansas3            Arkansas                        3
arkansas4            Arkansas                        4
california1        California                        1
california2        California                        2
california3        California                        3
california4        California                        4
california5        California                        5
california6        California                        6
california7        California                        7
california8        California                        8
california9        California                        9
...                       ...                      ...
virginia4            Virginia                        4
virginia5            Virginia                        5
virginia6            Virginia                        6
virginia7            Virginia                        7
virginia8            Virginia                        8
virginia9            Virginia                        9
virginia10           Virginia                       10
virginia11           Virginia                       11
washington1        Washington                        1
washington2        Washington                        2
washington3        Washington                        3
washington4        Washington                        4
washington5        Washington                        5
washington6        Washington                        6
washington7        Washington                        7
washington8        Washington                        8
washington9        Washington                        9
washington10       Washington                       10
west_virginia1  West Virginia                        1
west_virginia2  West Virginia                        2
west_virginia3  West Virginia                        3
wisconsin1          Wisconsin                        1
wisconsin2          Wisconsin                        2
wisconsin3          Wisconsin                        3
wisconsin4          Wisconsin                        4
wisconsin5          Wisconsin                        5
wisconsin6          Wisconsin                        6
wisconsin7          Wisconsin                        7
wisconsin8          Wisconsin                        8
wyoming1              Wyoming                        1

[437 rows x 2 columns]